### ISSUE TITLE
Failed to read JSON

### ISSUE THREAD

**Issue by TriplEight** [insipx/polkadot-rewards#98]
How do I debug/work around the following issue:

```bash
$ polkadot-rewards --from "2020-01-01 00:00:00" --to "2020-12-31 23:59:59" --network "DOT" --address "xx" --currency "eur"
Error: Failed to fetch prices.

Caused by:
    Failed to read JSON: missing field `market_data` at line 1 column 810
```

**Comment by insipx** [comment]
subscan or coingecko API JSON format probably changed, I will push a fix in the next 24 hours or so and a new version to fix this

**Comment by TriplEight** [comment]
I think I figured it, I was including the dates when polkadot was not yet launched, starting ` --from "2020-08-19 00:00:00" ` solved my problem

**Comment by TriplEight** [comment]
then it could've been just handled gracefully

**Comment by insipx** [comment]
Ah i see, glad you found a solution

can i consider this issue solved then?
